In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
df = pd.read_csv('data.csv')

x = df.iloc[0: , :-1].values
y = df.iloc[: , -1].values

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan , strategy='mean')
imputer.fit(x[:,1:3])

x[:,1:3] = imputer.transform(x[:,1:3])



FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
le = LabelEncoder()
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

x = np.array(ct.fit_transform(x))
y = le.fit_transform(y)





NameError: name 'x' is not defined

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x_train , y_train , x_test , y_test = train_test_split(x,y,test_size=0.2 , random_state=1)


sc = StandardScaler()


x_train = sc.fit_transform(x_train)
y_train = sc.fit_transform(y_train)

print(x_train)



[[-0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [-0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [ 1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [-0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [-0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [ 1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [-0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [ 1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]


In [26]:
print(y_train)

[[-0.70710678  0.70710678  0.          1.37281295  1.4027157 ]
 [-0.70710678  0.70710678  0.         -0.98058068 -0.85721515]
 [ 1.41421356 -1.41421356  0.         -0.39223227 -0.54550055]]


In [52]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(x_train , y_train)

predictor = regressor.predict(x_test)

#plt.scatter(x_train, y_train, color='red')

#plt.plot(x_train, regressor.predict(x_train), color='blue')

regressor.intercept_(x_train)


ValueError: Found input variables with inconsistent numbers of samples: [8, 2]