In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [4]:
  from sklearn.datasets import make_classification

In [6]:
###Create the Dataset
x , y = make_classification(n_samples=1000, n_features=10, n_classes=2)

In [7]:
x

array([[-1.05171501,  0.28258434,  1.82126373, ..., -0.19325958,
         0.02882046,  0.92247063],
       [-1.09455748,  0.57826112, -0.5455684 , ...,  0.65761383,
         0.33764043, -0.25892442],
       [ 0.21013529,  1.10745372,  0.23849098, ..., -1.22386115,
         0.66933034,  4.43294877],
       ...,
       [ 0.6063968 , -1.01033395, -0.3185459 , ..., -1.14744939,
        -0.6368074 , -0.85006225],
       [-1.53813904,  2.03792235,  0.14730421, ...,  0.48782064,
         1.95800174, -0.10567364],
       [ 0.18160409, -1.77190373,  1.49575971, ..., -1.14310453,
        -1.51067406,  0.87441509]])

In [8]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9
0,-1.051715,0.282584,1.821264,0.919616,0.405310,0.749725,0.221637,-0.193260,0.028820,0.922471
1,-1.094557,0.578261,-0.545568,0.866500,-0.017325,-0.053754,1.473050,0.657614,0.337640,-0.258924
2,0.210135,1.107454,0.238491,1.576762,-0.102155,0.282214,1.629317,-1.223861,0.669330,4.432949
3,0.959028,-0.234668,-0.208500,-1.127921,-0.640333,0.493585,1.074324,0.264105,0.076033,1.292365
4,-1.251931,0.490644,-1.473361,-0.489024,-1.035627,1.398740,0.738223,0.237570,0.622478,-1.290758
...,...,...,...,...,...,...,...,...,...,...
995,-0.912019,2.609945,-0.834743,2.801783,-1.003118,0.215114,0.771987,-1.397535,1.828318,-0.366448
996,0.373106,-1.231363,2.838207,-2.019869,-0.108815,-0.207483,-0.124681,-0.485255,-0.671025,-0.251037
997,0.606397,-1.010334,-0.318546,-1.343115,0.172729,2.364366,0.585737,-1.147449,-0.636807,-0.850062
998,-1.538139,2.037922,0.147304,0.255163,-2.394879,0.070858,0.032064,0.487821,1.958002,-0.105674


In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state = 42)


In [10]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()
logistic.fit(x_train,y_train)

LogisticRegression()

In [12]:
y_pred = logistic.predict(x_test)
print(y_pred)

[1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0
 1 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 1 0
 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1 1 1 1
 1 0 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1
 1 1 0 0 0 1 0 1 1 0 0 1 0 1 0]


In [15]:
logistic.predict_proba(x_test)

array([[5.21852742e-02, 9.47814726e-01],
       [7.64670650e-01, 2.35329350e-01],
       [7.53088574e-03, 9.92469114e-01],
       [9.47908327e-02, 9.05209167e-01],
       [7.22143984e-01, 2.77856016e-01],
       [3.48897841e-02, 9.65110216e-01],
       [9.99650786e-01, 3.49213794e-04],
       [9.30443649e-01, 6.95563511e-02],
       [5.51719839e-03, 9.94482802e-01],
       [7.21343970e-02, 9.27865603e-01],
       [6.19345798e-01, 3.80654202e-01],
       [3.47268706e-02, 9.65273129e-01],
       [7.74791127e-02, 9.22520887e-01],
       [7.67552882e-01, 2.32447118e-01],
       [7.03053604e-03, 9.92969464e-01],
       [9.61814287e-01, 3.81857129e-02],
       [7.87389500e-01, 2.12610500e-01],
       [1.75347538e-02, 9.82465246e-01],
       [3.24261623e-01, 6.75738377e-01],
       [8.48742195e-01, 1.51257805e-01],
       [5.27516548e-02, 9.47248345e-01],
       [8.98883538e-01, 1.01116462e-01],
       [6.66834400e-01, 3.33165600e-01],
       [9.23910380e-01, 7.60896201e-02],
       [9.555833

In [16]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report

cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_test,y_pred))
print(cm)

0.8
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       103
           1       0.79      0.79      0.79        97

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.80      0.80      0.80       200

[[83 20]
 [20 77]]


In [17]:
### Hyperparameter and Cross validation

model = LogisticRegression()
penalty = ['l1','l2' , 'elasticnet']
c = [100,10,1.0,0.1,0.01]
solver = ['newton-cg' , 'lbfgs' , 'liblinear' , 'sag' , 'saga']

In [26]:
params = dict(penalty = penalty , C = c , solver = solver)

In [32]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [33]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator = model ,param_grid = params , scoring = 'accuracy' ,cv=cv, n_jobs = -1)


In [34]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [35]:
grid.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solv

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [36]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [37]:
grid.best_score_

0.8487500000000001